/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

import java.awt.Cursor;
import java.text.DecimalFormat;

/**
 *
 * @author Andrea Merici
 */
public class myJFrame extends javax.swing.JFrame {

    // Direction of the conversion (if true, miles are converted into kilometers)
    public static boolean CONVERSION_MI_TO_KM = true;

    /**
     * Creates new form myJFrame
     */
    public myJFrame() {
        initComponents();
        setUnitMeasures();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        valueField1 = new javax.swing.JTextField();
        factorLabel = new javax.swing.JLabel();
        valueField2 = new javax.swing.JLabel();
        changeButton = new javax.swing.JButton();
        unitMeasureLabel1 = new javax.swing.JLabel();
        unitMeasureLabel2 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(102, 102, 255));
        titleLabel.setText("UNIT CONVERSION");

        valueField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valueField1KeyReleased(evt);
            }
        });

        factorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        factorLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        valueField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        changeButton.setText("Change");
        changeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeButtonMouseExited(evt);
            }
        });
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        unitMeasureLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        unitMeasureLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(factorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueField2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valueField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unitMeasureLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unitMeasureLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(changeButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(factorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(unitMeasureLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valueField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(valueField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unitMeasureLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(changeButton)
                        .addGap(16, 16, 16)))
                .addGap(18, 18, 18)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method associated with the pressing of the 'Change' button
     * @param evt: ActionEvent 
     */
    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        
        // Change the direction of conversion
        CONVERSION_MI_TO_KM = !CONVERSION_MI_TO_KM;
        
        // Reset the errorLabel
        errorLabel.setText("");
        
        setUnitMeasures();
    }//GEN-LAST:event_changeButtonActionPerformed

    /**
     * Method associated with the changes int the first field
     * @param evt: KeyEvent 
     */
    private void valueField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valueField1KeyReleased
        
        // Reset the errorLabel
        errorLabel.setText("");
        
        String input = valueField1.getText();
        
        if(input.length() != 0){
            
            // The input is numeric
            if(isNumeric(input)){
                double valueEntered = Float.parseFloat(input);
                double valueConverted = conversion(valueEntered);
            
                // Format of the number with 3 digits
                DecimalFormat df = new DecimalFormat("###.###");
                String result = df.format(valueConverted);
                valueField2.setText(result);
            
            }else if (input.charAt(input.length()-1) == '.'){
                // If the last digit is '.', reset and wait for the next digit
                errorLabel.setText("");
                valueField2.setText("");
            
            }else{
                errorLabel.setText("The entered value is not correct");
                valueField2.setText("");
            }
        }

    }//GEN-LAST:event_valueField1KeyReleased

    /**
     * Events for changing the cursor
     * @param evt: MouseEvent 
     */
    private void changeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_changeButtonMouseEntered

    private void changeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseExited
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_changeButtonMouseExited
           
    /**
     * Method for the setting of the conversion options
     */
    public void setUnitMeasures(){
        if(CONVERSION_MI_TO_KM){
            factorLabel.setText("1 mi = 1.609 km");
            unitMeasureLabel1.setText("mi");
            unitMeasureLabel2.setText("km");   
        }else{
            factorLabel.setText("1 km = 0.621 mi");
            unitMeasureLabel1.setText("km");
            unitMeasureLabel2.setText("mi"); 
        }
        
        // Reset the field value
        valueField1.setText("");
        valueField2.setText("");
    }
        
    /**
     * Method for checking if one string is a numeric value
     * @param str
     * @return true if the string respects the Regular Expression
     */
    public static boolean isNumeric(final String str) {
        
        // In this Regular Expression 'd' is decimal
        return str.matches("\\d+(\\.\\d+)?");
    }

    /**
     * Method for the conversion of the value of measure
     * @param value: the value that has to be converted
     * @return the converted value
     */
    public double conversion(double value){
        
        double res;
        
        if(CONVERSION_MI_TO_KM){
            res = (value * 1.609);
        }else{
            res = (value / 1.609);
        }

        return res;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel factorLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel unitMeasureLabel1;
    private javax.swing.JLabel unitMeasureLabel2;
    private javax.swing.JTextField valueField1;
    private javax.swing.JLabel valueField2;
    // End of variables declaration//GEN-END:variables
}
